  <section className="product-hero"><div className="shell product-hero-grid"><ProductGallery images={handTapSetGallery} /><div className="product-summary"><p className="eyebrow">HSS hand tap set manufacturer · Ludhiana, India</p><h1>HSS Hand Tap Set<br /><em>3 Pieces</em></h1><p className="product-subtitle">Three stages. One practical set for hand threading.</p><p className="product-description">SWAGIN HSS hand tap sets combine taper, plug/intermediate and bottoming taps for suitable manual internal threading operations. Share your thread size, material, quantity and drawing reference for a standard, bulk, export or custom enquiry.</p><div className="product-facts"><span><b>3 pieces</b><small>Set contents</small></span><span><b>M2 · M35 · M42</b><small>Material grades</small></span><span><b>62–64 HRC</b><small>Listed hardness</small></span></div><div className="product-actions"><Link className="button button-yellow" href="#enquiry">Request a product quote <span aria-hidden="true">↗</span></Link><a className="product-phone" href={company.phoneHref}>Call manufacturer<br /><strong>{company.phone}</strong></a></div><div className="product-quick-links"><a href="#specifications">Specifications</a><a href="#applications">Applications</a><a href="#faqs">FAQs</a></div></div></div></section>
import Image from "next/image";
import Link from "next/link";
import { ProductEnquiryForm } from "@/components/product-enquiry-form";
import { ProductGallery } from "@/components/product-gallery";
import { SiteShell } from "@/components/site-shell";
import { company } from "@/data/site";
import { handTapIndustries, handTapSetFaqs, handTapSetGallery, handTapSetSpecs, handTapThreadFamilies } from "@/data/hand-tap";

export const metadata = {
  title: "HSS Hand Tap Set Manufacturer in India | Swastik Grand Industries",
  description: "SWAGIN three-piece HSS hand tap sets with taper, plug/intermediate and bottoming taps. Discuss sizes, specifications, bulk, export and custom requirements.",
};

const features = [
  ["Three-stage sequence", "Taper, plug/intermediate and bottoming taps support staged internal thread formation in a prepared hole."],
  ["HSS grade options", "Discuss M2, M35 or M42 according to the workpiece material and application."],
  ["Ground-thread finish", "Supports controlled thread formation and dimensional review for the selected configuration."],
  ["Thread-family choice", "Metric, British, unified and pipe-thread requirements can be reviewed against the exact specification."],
  ["Lead options", "Select 6-thread taper, 4-thread plug/intermediate or 2-thread bottoming geometry where suitable."],
  ["Bulk and custom review", "Share size-wise quantities, drawings, dimensions and commercial requirements for quotation."],
];

export default function HssHandTapSetPage() {
  const productJsonLd = { "@context": "https://schema.org", "@type": "Product", name: "SWAGIN HSS Hand Tap Set - 3 Pieces", brand: { "@type": "Brand", name: "SWAGIN" }, manufacturer: { "@type": "Organization", name: company.name }, countryOfOrigin: "India", description: "Three-piece HSS hand tap set with taper, plug/intermediate and bottoming taps.", url: "https://swastikgrand.com/products/hss-threading-taps/hss-hand-tap-sets" };
  return <SiteShell><main id="top" className="product-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }} />
    <nav className="shell breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/products">Products</Link><span aria-hidden="true">/</span><Link href="/products/hss-threading-taps">HSS Threading Taps</Link><span aria-hidden="true">/</span><strong aria-current="page">HSS Hand Tap Set - 3 Pieces</strong></nav>
    <section className="product-hero"><div className="shell product-hero-grid"><ProductGallery images={handTapSetGallery} /><div className="product-summary"><p className="eyebrow">HSS hand tap set manufacturer · Ludhiana, India</p><h1>HSS Hand Tap Set<br /><em>3 Pieces</em></h1><p className="product-subtitle">Three stages. One practical set for hand threading.</p><p className="product-description">SWAGIN HSS hand tap sets combine taper, plug/intermediate and bottoming taps for suitable manual internal threading operations. Share your thread size, material, quantity and drawing reference for a standard, bulk, export or custom enquiry.</p><div className="product-facts"><span><b>3 pieces</b>Set contents</span><span><b>M2 · M35 · M42</b>Material grades</span><span><b>62–64 HRC</b>Listed hardness</span></div><div className="product-actions"><Link className="button button-yellow" href="#enquiry">Request a product quote <span aria-hidden="true">↗</span></Link><a className="product-phone" href={company.phoneHref}>Call manufacturer<br /><strong>{company.phone}</strong></a></div><div className="product-quick-links"><a href="#specifications">Specifications</a><a href="#applications">Applications</a><a href="#faqs">FAQs</a></div></div></div></section>
    <section className="product-overview section"><div className="shell product-two-column"><div><p className="eyebrow">Product overview</p><h2>A complete sequence for controlled internal threading.</h2></div><div><p>A three-piece hand tap set provides taper, plug/intermediate and bottoming options for suitable manual threading work in prepared holes. The correct sequence depends on the hole type, thread depth, material, alignment and component requirement.</p><p className="callout">Product-family information is a starting point. Confirm size-specific dimensions, grade, tolerance, availability and commercial terms in the quotation.</p></div></div></section>
    <section className="product-features section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Built around the application</p><h2>Three tools.<br /><em>One clear route.</em></h2></div><p>Review the set against the thread standard, workpiece material, hole type, depth and production quantity. No universal suitability or tool-life result is guaranteed.</p></div><div className="feature-grid">{features.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section id="specifications" className="section specifications"><div className="shell product-two-column"><div><p className="eyebrow">Technical information</p><h2>Confirm the right set configuration.</h2><p className="section-note">These product-family details guide the enquiry. Confirm the selected size, grade, tolerance, reference and availability in your quotation.</p></div><div className="spec-table">{handTapSetSpecs.map(([label, value]) => <div key={label}><strong>{label}</strong><span>{value}</span></div>)}</div></div></section>
    <section className="thread-section section"><div className="shell thread-grid"><div><p className="eyebrow">Thread families</p><h2>Find the thread<br /><em>you need.</em></h2><p>These are enquiry options, not live inventory claims. Send the exact drawing where the thread designation or standard is ambiguous.</p></div><div className="thread-panels">{handTapThreadFamilies.map(([group, options]) => <div key={group}><strong>{group}</strong><span>{options}</span></div>)}</div></div></section>
    <section className="lead-section section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Set contents</p><h2>Start clean.<br /><em>Finish close.</em></h2></div><p>Use each lead according to the entry, thread depth and hole condition. The corresponding configuration is confirmed in the quotation.</p></div><div className="lead-grid"><article><span>01</span><h3>Taper tap</h3><strong>6-thread lead</strong><p>Longer entry lead for progressively starting the thread.</p></article><article><span>02</span><h3>Plug / intermediate</h3><strong>4-thread lead</strong><p>Intermediate lead for continuing a tapping operation.</p></article><article><span>03</span><h3>Bottoming tap</h3><strong>2-thread lead</strong><p>Shorter lead for finishing nearer the bottom of a prepared blind hole.</p></article></div></div></section>
    <section id="applications" className="applications-section section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Application examples</p><h2>Your component.<br /><em>Your industry.</em></h2></div><p>Discuss the drawing, material, machine, hole and production quantity with the manufacturer. These examples do not claim customer or project approval.</p></div><div className="industry-grid">{handTapIndustries.slice(0, 6).map(([title, text, image], index) => <article key={title}><div className="industry-image"><Image src={image} alt={`${title} HSS tap set application example`} fill sizes="(max-width: 560px) 100vw, (max-width: 900px) 50vw, 33vw" /></div><div className="industry-copy"><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p><a href={`/products/hss-threading-taps/hss-hand-tap-sets?industry=${encodeURIComponent(title)}#enquiry`}>Discuss this application <span aria-hidden="true">↗</span></a></div></article>)}</div></div></section>
    <section id="enquiry" className="product-enquiry section"><div className="shell product-two-column"><div><p className="eyebrow">HSS hand tap set enquiry</p><h2>Tell us what you need.<br /><em>We will review the route.</em></h2><p>Share your thread, material, quantity or drawing reference. The enquiry is sent to the configured company inbox.</p><div className="contact-list"><a href={company.phoneHref}>{company.phone}</a><a href={`mailto:${company.email}`}>{company.email}</a><a href={company.whatsapp} target="_blank" rel="noreferrer">WhatsApp us <span aria-hidden="true">↗</span></a></div></div><ProductEnquiryForm productName="HSS Hand Tap Set - 3 Pieces" /></div></section>
    <section id="faqs" className="faq-section section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Buyer questions</p><h2>Clear answers<br /><em>before you order.</em></h2></div></div><div className="faq-list">{handTapSetFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="related-products section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Continue exploring</p><h2>Related tools<br /><em>for the job.</em></h2></div><p>Review the individual hand tap route or return to all product families when the application needs a different tooling approach.</p></div><div className="related-grid"><Link href="/products/hss-threading-taps/hss-hand-taps"><Image src="/images/products/hss-hand-tap.jpg" alt="HSS Threading Hand Tap" fill sizes="(max-width: 560px) 100vw, 33vw" /><strong>HSS Threading Hand Tap</strong></Link><Link href="/products"><Image src="/images/products/hss-machine-tap.jpg" alt="HSS machine tap" fill sizes="(max-width: 560px) 100vw, 33vw" /><strong>View all products</strong></Link></div></div></section>
    <div className="mobile-contact-bar"><a href={company.phoneHref}>Call</a><a href={company.whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><a href="#enquiry">Request quote</a></div>
  </main></SiteShell>;
}
