import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { CustomTapShowcase } from "@/components/custom-tap-showcase";
import { SiteShell } from "@/components/site-shell";

export const metadata: Metadata = { title: "Custom Taps | Swastik Grand Industries", description: "Discuss custom tap manufacturing for special thread sizes, extended lengths and drawing-based requirements." };

const specifications = ["Special thread sizes and pitches", "Long shank and extended-length requirements", "Material grade and coating options", "Right-hand and left-hand threads", "Drawing or sample-based tooling", "Repeat production requirements"];

const customProducts = [
  ["HSS Reamers", "Hole finishing", "Refine prepared holes where diameter, tolerance, reach and material need to be matched.", "/images/products/hss-reamers.jpg", "/products/hss-reamers"],
  ["HSS End Mill Cutters", "Milling and slotting", "Discuss diameter, flute form, reach and profile requirements for suitable milling work.", "/images/products/hss-end-mill-cutter.jpg", "/products/milling-gear-cutters/hss-end-mill-cutters"],
  ["HSS Gear Hob Cutters", "Gear manufacturing", "Share module, pressure angle, helix, bore and gear details for a drawing-led review.", "/images/products/hss-gear-hob-cutter.jpg", "/products/milling-gear-cutters/hss-gear-hob-cutters"],
  ["Threading Dies & Rolls", "External thread forming", "Review round dies and circular rolls against thread profile, blank, material and machine.", "/images/products/circular-thread-roll.jpg", "/products/threading-dies-rolls"],
  ["HSS Tool Bits", "Turning and shaping", "Specify round or square section, length, grade and custom-ground profile for the operation.", "/images/products/hss-round-tool-bit.png", "/products/hss-tool-bits"],
  ["HSS Threading Taps", "Internal threading", "Choose hand, machine, nut, ACME, SPPT, forming or insert-thread preparation routes.", "/images/products/hss-machine-tap.jpg", "/products/hss-threading-taps"],
  ["Special Cutters", "Application-specific tooling", "Discuss cutter dimensions, profile, material and machine requirements from a drawing or sample.", "/images/products/hss-cutter.jpg", "/get-a-quote?product=HSS%20Cutter"],
  ["Custom Tooling Review", "One requirement, one conversation", "When the standard catalogue does not fit, send the component details and our team can review feasibility.", "/images/products/hss-heli-coil-tap.jpg", "/get-a-quote?enquiryType=Custom"],
];

export default function CustomTapsPage() {
  return <SiteShell><main id="top" className="inner-page custom-page"><section className="custom-hero"><div className="shell custom-hero-grid"><div><p className="eyebrow">Custom tap manufacturing</p><h1>Your drawing.<br /><em>Our expertise.</em><br />A tool that fits.</h1><p>When standard taps do not meet your requirements, share your drawing, sample details or thread specification with Swastik Grand Industries.</p><Link className="button button-yellow" href="/get-a-quote">Discuss your custom tap <span aria-hidden="true">↗</span></Link></div><div className="custom-spec-panel"><p className="detail-title">Built around your requirement</p><div className="spec-list">{specifications.map((specification) => <span key={specification}>{specification}</span>)}</div><p className="drawing-note">Have a drawing or sample?<br /><a href="mailto:info@swastikgrand.com">Email it to info@swastikgrand.com <span aria-hidden="true">↗</span></a></p></div></div></section><CustomTapShowcase /><section className="section custom-products"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Beyond custom taps</p><h2>One drawing.<br /><em>Many tool routes.</em></h2></div><p>Custom requirements can extend beyond threading. Explore the wider SWAGIN range and share your dimensions, material, machine, quantity or component drawing for a practical feasibility review.</p></div><div className="custom-products-grid">{customProducts.map(([title, category, description, image, href], index) => <article className="custom-product-card" key={title}><div className="custom-product-image"><Image src={image} alt={title} fill sizes="(max-width: 560px) 100vw, (max-width: 900px) 50vw, 25vw" /><span>0{index + 1}</span></div><div className="custom-product-copy"><p>{category}</p><h3>{title}</h3><span>{description}</span><Link href={href}>Discuss this product <b aria-hidden="true">↗</b></Link></div></article>)}</div></div></section><section className="section custom-process"><div className="shell"><div className="section-heading"><div><p className="eyebrow">A clear path to the right tool</p><h2>From requirement<br /><em>to production.</em></h2></div><p>Share the details you have. We&apos;ll use the application context to discuss the right geometry, material and finish for your use.</p></div><div className="custom-process-grid"><article><span>01</span><h3>Share the requirement</h3><p>Send a drawing, sample, thread size, pitch or application detail.</p></article><article><span>02</span><h3>Review the solution</h3><p>Discuss tool geometry, shank length, material, coating and quantity.</p></article><article><span>03</span><h3>Make with confidence</h3><p>Move forward with a tool shaped around the work it needs to do.</p></article></div></div></section></main></SiteShell>;
}