import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProductEnquiryForm } from "@/components/product-enquiry-form";
import { SiteShell } from "@/components/site-shell";
import { categories, company } from "@/data/site";
import { productMenu } from "@/data/menu";
import type { Metadata } from "next";

const imageByLabel: Record<string, string> = {
  "HSS Hand Tap Sets": "/images/products/hss-hand-tap-set.jpg",
  "HSS Machine Taps": "/images/products/hss-machine-tap.jpg",
  "HSS Nut Taps": "/images/products/hss-nut-tap.jpg",
  "HSS Short Nut Taps": "/images/products/hss-short-nut-tap.jpg",
  "HSS Spiral Point Taps (SPPT)": "/images/products/hss-sppt-tap.jpg",
  "HSS ACME Thread Taps": "/images/products/hss-acme-tap.jpg",
  "HSS Thread Forming Roll Taps": "/images/products/hss-thread-forming-roll-tap.jpg",
  "HSS Heli-Coil STI Taps": "/images/products/hss-heli-coil-tap.jpg",
  "HSS Round Thread Cutting Dies": "/images/products/hss-round-thread-cutting-die.jpg",
  "Circular Thread Rolling Dies": "/images/products/circular-thread-roll.jpg",
  "HSS End Mill Cutters": "/images/products/hss-end-mill-cutter.jpg",
  "HSS Gear Hob Cutters": "/images/products/hss-gear-hob-cutter.jpg",
  "HSS Round Tool Bits": "/images/products/hss-round-tool-bit.png",
  "HSS Square Tool Bits": "/images/products/hss-square-tool-bit.jpg",
};

type ProductDetails = { subtitle: string; description: string; overview: string; facts: [string, string, string]; features: [string, string][]; specifications: [string, string][]; applications: string };

const productDetails: Record<string, ProductDetails> = {
  "HSS Hand Tap Sets": { subtitle: "Three stages. One practical set for hand threading.", description: "A three-piece set with taper, plug / intermediate and bottoming taps for suitable manual internal threading operations.", overview: "Use the taper, plug and bottoming sequence when the application calls for staged thread formation in a prepared hole.", facts: ["3 pieces", "M2 / M35 / M42", "62-64 HRC"], features: [["Taper, plug and bottoming", "A practical three-tool sequence for starting, continuing and finishing a thread."], ["Ground-thread finish", "Supports controlled thread formation and dimensional review."], ["Bulk-ready discussion", "Share size-wise quantities, drawings and delivery requirements for quotation."]], specifications: [["Set contents", "Taper, plug / intermediate and bottoming taps"], ["Material grades", "M2 (HSS), M35 (HSS-E), M42 (HSS-ECO)"], ["Listed size range", "6 mm to 100 mm"], ["Finish", "Ground thread"]], applications: "Tool rooms, workshops, repair work and selected small-batch component threading." },
  "HSS Machine Taps": { subtitle: "Threading tools for suitable machine operations.", description: "HSS machine taps for controlled internal threading where the machine, hole preparation and cutting conditions are reviewed together.", overview: "Machine tap selection depends on machine type, material, hole form, thread depth, chip evacuation and the required production cycle.", facts: ["HSS options", "Machine-led", "Quote confirmed"], features: [["Machine compatibility", "Review spindle, alignment, workholding and tapping cycle before selection."], ["Thread-form options", "Confirm thread standard, pitch, tolerance and geometry against the drawing."], ["Production review", "Discuss repeat quantity, inspection requirements and expected delivery."]], specifications: [["Product type", "HSS machine tap"], ["Application", "Machine threading in suitable prepared holes"], ["Selection", "Material, thread, tolerance and machine dependent"], ["Commercial terms", "Confirmed in quotation"]], applications: "General engineering, component manufacturing, fabrication and tool-room production." },
  "HSS Nut Taps": { subtitle: "A focused route for internal nut threading requirements.", description: "HSS nut taps for suitable repeated internal threading applications, with selection based on nut material, size, machine and production quantity.", overview: "Nut production often needs a dedicated tap geometry and process review rather than an automatic substitution of a general hand tap.", facts: ["Nut production", "Size-wise quote", "Process review"], features: [["Application-specific", "Discuss nut material, thread, machine and target production quantity."], ["Repeat requirements", "Share size lists and repeat schedules for a practical commercial review."], ["Quality context", "Confirm gauge, tolerance, inspection and acceptance requirements."]], specifications: [["Product type", "HSS nut tap"], ["Application", "Suitable internal nut threading"], ["Selection", "Nut material, thread, machine and quantity"], ["Availability", "Confirmed for selected configuration"]], applications: "Fasteners, nuts and selected repeated internal-thread production." },
  "HSS Short Nut Taps": { subtitle: "Compact geometry for selected nut-threading work.", description: "HSS short nut taps for applications where the component and process call for a shorter tool format, subject to drawing and machine review.", overview: "Confirm access, thread length, machine setup and chip handling before selecting a short nut tap.", facts: ["Short format", "HSS grades", "Drawing-led"], features: [["Compact option", "Review tool envelope and component access against the production setup."], ["Nut-thread focus", "Match thread, material, tolerance and quantity to the selected tap."], ["Custom review", "Share a drawing when the standard short format does not cover the requirement."]], specifications: [["Product type", "HSS short nut tap"], ["Use", "Selected internal nut-threading operations"], ["Key inputs", "Thread, material, length and machine"], ["Terms", "Confirmed in quotation"]], applications: "Fastener production, compact components and drawing-led nut-threading enquiries." },
  "HSS Spiral Point Taps (SPPT)": { subtitle: "Spiral point geometry for suitable through-hole threading.", description: "HSS spiral point taps, also known as SPPT, for suitable through-hole applications where chip movement and machine conditions support the geometry.", overview: "Spiral point selection depends on through-hole access, material, machine cycle, lubrication and the required thread specification.", facts: ["SPPT", "Through holes", "Machine review"], features: [["Spiral point geometry", "Discuss chip direction and through-hole conditions before selection."], ["Material matching", "Review grade, coating, thread form and workpiece material together."], ["Production fit", "Confirm machine, speed, quantity and inspection requirements in the enquiry."]], specifications: [["Product type", "HSS Spiral Point Tap (SPPT)"], ["Typical route", "Suitable through-hole threading"], ["Selection", "Material, machine, thread and chip flow"], ["Availability", "Confirmed in quotation"]], applications: "Through-hole component threading, machine shops and selected production cycles." },
  "HSS ACME Thread Taps": { subtitle: "Thread-form tools for ACME profile requirements.", description: "HSS ACME thread taps for suitable internal ACME thread applications where the profile, pitch and component drawing are confirmed.", overview: "ACME thread selection is drawing-led: confirm angle, pitch, diameter, tolerance, depth and the required tap sequence.", facts: ["ACME profile", "Drawing-led", "Custom review"], features: [["Profile-specific", "Confirm the ACME form and dimensions against the component requirement."], ["Application review", "Discuss material, hole depth, machine or hand operation and quantity."], ["Special sizes", "Submit a drawing for non-standard lengths, diameters or tolerances."]], specifications: [["Product type", "HSS ACME thread tap"], ["Thread profile", "ACME, subject to confirmed drawing"], ["Inputs", "Pitch, diameter, tolerance and depth"], ["Terms", "Confirmed in quotation"]], applications: "Lead screws, motion components, fixtures and suitable engineering assemblies." },
  "HSS Thread Forming Roll Taps": { subtitle: "Form internal threads without conventional chip cutting.", description: "HSS thread forming roll taps for suitable ductile materials where the material, pre-hole and forming process are technically appropriate.", overview: "Thread forming requires a compatible material and correctly prepared pre-hole; confirm the process before ordering.", facts: ["Thread forming", "Pre-hole critical", "Material review"], features: [["Chipless forming route", "Discuss whether material ductility and the process support thread forming."], ["Pre-hole control", "Confirm pre-hole diameter, tolerance, lubrication and machine cycle."], ["Process evidence", "Review inspection and acceptance criteria for the finished thread."]], specifications: [["Product type", "HSS thread forming roll tap"], ["Process", "Suitable internal thread forming"], ["Key inputs", "Material, pre-hole, pitch and machine"], ["Availability", "Configuration confirmed in quotation"]], applications: "Suitable ductile materials, repeat machine threading and process-specific enquiries." },
  "HSS Heli-Coil STI Taps": { subtitle: "STI thread preparation for suitable repair inserts.", description: "HSS Heli-Coil STI taps for preparing internal threads for compatible thread-repair insert systems, subject to the insert specification.", overview: "STI tapping must match the insert system, original thread requirement, hole condition and repair procedure.", facts: ["STI profile", "Insert-led", "Repair review"], features: [["Insert compatibility", "Confirm the exact Heli-Coil or compatible insert specification first."], ["Repair preparation", "Review damaged thread condition, depth, material and access."], ["Gauge and tolerance", "Discuss the required STI gauge and inspection method for the job."]], specifications: [["Product type", "HSS Heli-Coil STI tap"], ["Application", "Suitable insert-thread preparation"], ["Selection", "Insert system, thread, material and depth"], ["Terms", "Confirmed in quotation"]], applications: "Thread repair, maintenance, castings, housings and insert preparation work." },
  "HSS Round Thread Cutting Dies": { subtitle: "External thread cutting for suitable round-die work.", description: "HSS round thread cutting dies for suitable external threading requirements where the diameter, pitch, material and die setup are confirmed.", overview: "Die selection depends on the external thread standard, blank diameter, material, alignment and required tolerance.", facts: ["External threads", "HSS cutting", "Size quote"], features: [["Thread accuracy", "Confirm diameter, pitch, standard and tolerance against the drawing."], ["Material matching", "Review workpiece material, hardness and cutting conditions."], ["Standard or custom", "Discuss size-wise requirements, packaging and repeat quantities."]], specifications: [["Product type", "HSS round thread cutting die"], ["Application", "Suitable external thread cutting"], ["Inputs", "Thread standard, diameter, pitch and material"], ["Terms", "Confirmed in quotation"]], applications: "Repair work, fabrication, maintenance and suitable external-thread production." },
  "Circular Thread Rolling Dies": { subtitle: "Circular tooling for suitable thread rolling processes.", description: "Circular thread rolling dies for suitable external thread forming processes where the machine, blank and material are compatible.", overview: "Thread rolling is process-specific. Confirm machine tooling, blank size, material ductility, profile and production quantity.", facts: ["Thread rolling", "Circular die", "Process-led"], features: [["Forming process", "Review whether the blank and material support the rolling operation."], ["Profile control", "Confirm thread standard, pitch, diameter and acceptance method."], ["Production planning", "Discuss machine, repeat quantities, setup and delivery requirements."]], specifications: [["Product type", "Circular thread rolling die"], ["Application", "Suitable external thread rolling"], ["Selection", "Machine, blank, material and profile"], ["Terms", "Confirmed in quotation"]], applications: "Suitable production threading, fasteners and repeat external-thread operations." },
  "HSS End Mill Cutters": { subtitle: "Milling tools for suitable slotting and profile work.", description: "HSS end mill cutters for suitable milling applications where diameter, flute form, material and machine conditions are matched.", overview: "End mill selection depends on workpiece material, cut type, reach, machine rigidity and the required finish.", facts: ["Milling tool", "Flute review", "Application-led"], features: [["Cut geometry", "Confirm diameter, flute count, length and profile against the operation."], ["Machine fit", "Review spindle, workholding, reach and cutting conditions."], ["Custom options", "Discuss special dimensions or drawing-led cutter requirements."]], specifications: [["Product type", "HSS end mill cutter"], ["Use", "Suitable milling, slotting and profile work"], ["Inputs", "Material, diameter, flute and reach"], ["Terms", "Confirmed in quotation"]], applications: "General machining, slots, profiles, keyways and tool-room work." },
  "HSS Gear Hob Cutters": { subtitle: "Hob cutters for suitable gear manufacturing work.", description: "HSS gear hob cutters for suitable gear-cutting requirements where module, pressure angle, tooth form and machine details are confirmed.", overview: "Gear hob selection is drawing- and machine-led. Confirm module, pressure angle, helix, bore and gear specification.", facts: ["Gear cutting", "HSS tool", "Drawing-led"], features: [["Gear specification", "Match module, pressure angle, tooth form and helix to the gear drawing."], ["Machine compatibility", "Confirm hob machine, arbor, bore and setup requirements."], ["Inspection context", "Discuss gear accuracy, inspection method and required documentation."]], specifications: [["Product type", "HSS gear hob cutter"], ["Inputs", "Module, pressure angle, helix and bore"], ["Application", "Suitable gear manufacturing"], ["Terms", "Confirmed in quotation"]], applications: "Gear manufacturing, tool rooms and drawing-led industrial gear work." },
  "HSS Round Tool Bits": { subtitle: "Round HSS tool bits for turning and custom grinding.", description: "HSS round tool bits for suitable machining, custom grinding and tool-room applications where the required diameter and grade are confirmed.", overview: "Round tool-bit selection depends on holder, operation, workpiece material, diameter and the required ground profile.", facts: ["Round section", "Custom grind", "HSS option"], features: [["Tool-room flexibility", "Discuss blank diameter, length and the profile needed for the operation."], ["Material matching", "Review workpiece material and cutting purpose before selecting grade."], ["Custom grinding", "Share a drawing or profile reference for feasibility review."]], specifications: [["Product type", "HSS round tool bit"], ["Use", "Turning, shaping and custom grinding"], ["Inputs", "Diameter, length, profile and material"], ["Terms", "Confirmed in quotation"]], applications: "Tool rooms, turning, shaping, special profiles and maintenance work." },
  "HSS Square Tool Bits": { subtitle: "Square HSS tool bits for turning and shaping work.", description: "HSS square tool bits for suitable turning, shaping and custom-ground tool requirements where section, length and profile are confirmed.", overview: "Square tool-bit selection depends on holder size, operation, workpiece material and the required cutting profile.", facts: ["Square section", "Tool-room use", "Profile review"], features: [["Stable blank", "Confirm section, length and holder compatibility for the operation."], ["Custom profile", "Discuss the nose, rake or special form needed for the component."], ["Application fit", "Review material, machine and expected quantity before ordering."]], specifications: [["Product type", "HSS square tool bit"], ["Use", "Turning, shaping and custom grinding"], ["Inputs", "Section, length, profile and material"], ["Terms", "Confirmed in quotation"]], applications: "Turning, shaping, tool-room work and custom-ground cutting tools." },
};

function getProductDetails(label: string): ProductDetails {
  return productDetails[label] || { subtitle: "Made for the next operation.", description: `${label} for suitable workshop, tool-room and production requirements.`, overview: "Selection depends on the material, machine, dimensions, tolerance and component drawing.", facts: ["SWAGIN", "India", "Quote-led"], features: [["Specification first", "Review size, profile, material and dimensions against the requirement."], ["Application review", "Discuss machine, quantity and operating conditions."], ["Clear quotation", "Confirm the selected configuration and commercial terms before ordering."]], specifications: [["Product type", label], ["Selection", "Application and drawing dependent"], ["Manufacturer", "Swastik Grand Industries"], ["Terms", "Confirmed in quotation"]], applications: "General engineering, tool rooms, maintenance and suitable production work." };
}

export function generateStaticParams() {
  return productMenu.flatMap((category) => (category.children || []).filter((item) => item.href.split("/").length === 4).map((item) => ({ category: category.href.split("/").pop()!, product: item.href.split("/").pop()! })));
}

export async function generateMetadata({ params }: { params: Promise<{ category: string; product: string }> }): Promise<Metadata> {
  const { category: categorySlug, product: productSlug } = await params;
  const category = productMenu.find((item) => item.href.endsWith(`/${categorySlug}`));
  const product = category?.children?.find((item) => item.href.endsWith(`/${productSlug}`));
  if (!product) return {};
  const details = getProductDetails(product.label);
  return { title: `${product.label} Manufacturer in India | Swastik Grand Industries`, description: `${details.description} Discuss sizes, specifications, bulk orders and export requirements with Swastik Grand Industries.` };
}

export default async function ProductDetailPage({ params }: { params: Promise<{ category: string; product: string }> }) {
  const { category: categorySlug, product: productSlug } = await params;
  const category = productMenu.find((item) => item.href.endsWith(`/${categorySlug}`));
  const product = category?.children?.find((item) => item.href.endsWith(`/${productSlug}`));
  if (!category || !product) notFound();

  const image = imageByLabel[product.label] || categories.find((item) => item.title.toLowerCase().includes(product.label.toLowerCase().replace("hss ", "")))?.image || "/images/products/hss-hand-tap.jpg";
  const details = getProductDetails(product.label);
  const productName = product.label;

  return <SiteShell><main id="top" className="product-page">
    <div className="shell breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/products">Products</Link><span>/</span><Link href={category.href}>{category.label}</Link><span>/</span><strong aria-current="page">{product.label}</strong></div>
    <section className="product-hero"><div className="shell product-hero-grid"><div className="product-gallery"><div className="product-gallery-main"><Image src={image} alt={product.label} fill priority sizes="(max-width: 900px) 100vw, 54vw" className="product-gallery-image" /></div><p className="product-gallery-caption">{product.label}</p><p className="product-gallery-note">Product image shown for this product family. Confirm the selected configuration in your quotation.</p></div><div className="product-summary"><p className="eyebrow">SWAGIN product family</p><h1>{product.label}</h1><p className="product-subtitle">{details.subtitle}</p><p className="product-description">{details.description} Share the size, thread, workpiece material, quantity and drawing reference so Swastik Grand Industries can review the correct specification.</p><div className="product-facts">{details.facts.map((fact) => <span key={fact}><b>{fact}</b>Product specification</span>)}</div><div className="product-actions"><Link className="button button-yellow" href="#enquiry">Request a product quote <span aria-hidden="true">↗</span></Link><a className="product-phone" href={company.phoneHref}>Call manufacturer<br /><strong>{company.phone}</strong></a></div></div></div></section>
    <section className="product-overview section"><div className="shell product-two-column"><div><p className="eyebrow">Product overview</p><h2>{details.overview}</h2></div><div><p>{details.description} The suitable grade, geometry, thread form, tolerance, coating and dimensions depend on the material, machine and component drawing.</p><p className="callout">Product-family information is a starting point, not a live inventory or universal suitability claim. Confirm technical and commercial details in the quotation.</p></div></div></section>
    <section className="product-features section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Application-led review</p><h2>Details that help<br /><em>you choose.</em></h2></div><p>{details.applications}</p></div><div className="feature-grid">{details.features.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section id="specifications" className="section specifications"><div className="shell product-two-column"><div><p className="eyebrow">Technical information</p><h2>Confirm the right configuration.</h2><p className="section-note">These product-family details guide the enquiry. Confirm dimensions, grade, tolerance, availability and commercial terms in the quotation.</p></div><div className="spec-table">{details.specifications.map(([label, value]) => <div key={label}><strong>{label}</strong><span>{value}</span></div>)}</div></div></section>
    <section id="enquiry" className="product-enquiry section"><div className="shell product-two-column"><div><p className="eyebrow">{product.label} enquiry</p><h2>Tell us what you need.<br /><em>We will review the route.</em></h2><p>Share your dimensions, material, quantity or drawing reference. The form prepares an email draft for review.</p><div className="contact-list"><a href={company.phoneHref}>{company.phone}</a><a href={`mailto:${company.email}`}>{company.email}</a><a href={company.whatsapp} target="_blank" rel="noreferrer">WhatsApp us <span aria-hidden="true">↗</span></a></div></div><ProductEnquiryForm productName={productName} /></div></section>
    <section className="related-products section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Continue exploring</p><h2>Related tools<br /><em>for the job.</em></h2></div></div><div className="related-grid"><Link href="/products"><Image src="/images/products/hss-hand-tap.jpg" alt="HSS hand tap" fill sizes="(max-width: 560px) 100vw, 33vw" /><strong>View all products</strong></Link><Link href="/get-a-quote"><Image src="/images/products/hss-machine-tap.jpg" alt="HSS machine tap" fill sizes="(max-width: 560px) 100vw, 33vw" /><strong>Request a quote</strong></Link></div></div></section>
  </main></SiteShell>;
}
