import type { Metadata } from "next";
import { EnquiryForm } from "@/components/enquiry-form";
import { SiteShell } from "@/components/site-shell";
import { company } from "@/data/site";

export const metadata: Metadata = { title: "Contact Us | Swastik Grand Industries", description: "Contact Swastik Grand Industries in Ludhiana for HSS taps, threading tools and industrial tooling enquiries." };

export default function ContactPage() {
  return <SiteShell><main id="top" className="inner-page contact-page"><section className="inner-hero"><div className="shell inner-hero-grid"><div><p className="eyebrow">Contact us</p><h1>Looking for the right tap?<br /><em>Let&apos;s talk.</em></h1></div><p>Welcome to Swastik Grand Industries, a leading manufacturer of HSS taps, nut taps, machine taps, hand taps and thread rolls in Ludhiana, Punjab, India.</p></div></section><section className="section contact-main"><div className="shell contact-layout"><div className="contact-copy"><p className="eyebrow">Schedule a consultation</p><h2>We&apos;re here<br /><em>to help.</em></h2><p>Tell us about your material, thread, quantity or production requirement. Our team will help you discuss a suitable tooling solution.</p><div className="contact-details"><p><strong>Mailing address</strong><br />{company.address}</p><p><strong>Email</strong><br /><a href={`mailto:${company.email}`}>{company.email}</a></p><p><strong>Call us today</strong><br /><a href={company.phoneHref}>{company.phone}</a></p><a className="under-link" href={company.whatsapp} target="_blank" rel="noreferrer">Message us on WhatsApp <span aria-hidden="true">↗</span></a></div></div><div><p className="eyebrow">Send us a message</p><EnquiryForm /></div></div></section><section className="contact-map-section"><div className="shell contact-map-grid"><div><p className="eyebrow">Find us in Ludhiana</p><h2>Come talk<br /><em>tooling.</em></h2><p>Visit Swastik Grand Industries in Janta Nagar, Ludhiana, Punjab, India.</p><a className="under-link" href="https://maps.app.goo.gl/ho4jTPEUWHkCh7M29" target="_blank" rel="noreferrer">Open in Google Maps <span aria-hidden="true">↗</span></a></div><div className="map-frame"><iframe title="Swastik Grand Industries location map" src="https://www.google.com/maps?q=30.8799211,75.8620451&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section></main></SiteShell>;
}