import Image from "next/image";
import Link from "next/link";
import { SiteShell } from "@/components/site-shell";
import { ProductGallery } from "@/components/product-gallery";
import { ProductEnquiryForm } from "@/components/product-enquiry-form";
import { company } from "@/data/site";
import { handTapFaqs, handTapIndustries, handTapSpecs, handTapThreadFamilies } from "@/data/hand-tap";

export const metadata = {
  title: "HSS Hand Tap Manufacturer in India | Swastik Grand Industries",
  description: "SWAGIN HSS hand taps from Ludhiana: M2, M35 and M42 options. Discuss tool-room and component-threading requirements for bulk, export or custom orders.",
};

const leadOptions = [["Taper", "6 threads", "Longer entry lead for progressively starting the thread."], ["Plug / intermediate", "4 threads", "Intermediate lead for continuing a tapping operation."], ["Bottoming", "2 threads", "Shorter lead for finishing nearer the bottom of a prepared blind hole."]];
const features = [["HSS grade options", "Discuss M2, M35 or M42 according to the application and material."], ["Ground-thread finish", "Supports controlled thread formation and dimensional requirements."], ["Straight-flute options", "Listed 4- or 6-flute configurations; availability depends on selected size."], ["Manual control", "Intended for suitable tap-handle operations where alignment and preparation matter."], ["Custom enquiries", "Review non-standard sizes, lengths or drawing requirements for feasibility."], ["Quotation clarity", "Confirm size-specific dimensions, grade, coating, tolerance and terms before ordering."]];

export default function HssHandTapPage() {
  const productJsonLd = { "@context": "https://schema.org", "@type": "Product", name: "SWAGIN HSS Threading Hand Tap", brand: { "@type": "Brand", name: "SWAGIN" }, manufacturer: { "@type": "Organization", name: company.name }, countryOfOrigin: "India", description: "HSS hand taps for suitable controlled internal threading applications.", url: "https://swastikgrand.com/products/hss-hand-taps/hss-hand-tap" };
  return <SiteShell><main id="top" className="product-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }} />
    <div className="shell breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/products/hss-hand-taps">HSS Threading Taps</Link><span>/</span><span>Hand Taps</span><span>/</span><strong aria-current="page">HSS Threading Hand Tap</strong></div>
    <section className="product-hero"><div className="shell product-hero-grid"><ProductGallery /><div className="product-summary"><p className="eyebrow">HSS hand tap manufacturer · Ludhiana, India</p><h1>HSS Threading<br /><em>Hand Taps</em></h1><p className="product-subtitle">Precision threads. Longer tool life. Value that works for your business.</p><p className="product-description">Manufactured by Swastik Grand Industries, SWAGIN HSS hand taps support controlled internal threading in suitable workpiece materials. Share your thread size, material, drawing and quantity for a standard, bulk, export or custom-made enquiry.</p><div className="product-facts"><span><b>M2 · M35 · M42</b>Material grades</span><span><b>6–100 mm</b>Listed size range</span><span><b>62–64 HRC</b>Listed hardness</span></div><div className="product-actions"><Link className="button button-yellow" href="#enquiry">Request a product quote <span aria-hidden="true">↗</span></Link><a className="product-phone" href={company.phoneHref}>Call manufacturer<br /><strong>{company.phone}</strong></a></div><div className="product-quick-links"><a href="#specifications">Specifications</a><a href="#applications">Applications</a><a href="#faqs">FAQs</a></div></div></div></section>
    <section className="product-overview section"><div className="shell product-two-column"><div><p className="eyebrow">Product overview</p><h2>A dependable tool for controlled internal threading.</h2></div><div><p>SWAGIN HSS hand taps cut internal threads in prepared holes using a suitable tap handle. Precision-ground threads and straight-flute options provide a practical approach to manual workshop threading, component preparation and selected maintenance jobs.</p><p>The product family includes different grades, thread forms, tolerances and lead lengths. Correct selection depends on the material, its hardness, the hole type, required thread depth and the component drawing.</p><p className="callout">A hand tap is not automatically appropriate for every machine or high-volume production cycle. Share the process so the team can review the correct tool family.</p></div></div></section>
    <section className="product-features section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Built around the application</p><h2>Details that help<br /><em>you choose.</em></h2></div><p>Features and options are discussed against the material, thread, hole and production requirement. No tool-life, breakage or cost-saving result is guaranteed without relevant evidence.</p></div><div className="feature-grid">{features.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section id="specifications" className="section specifications"><div className="shell product-two-column"><div><p className="eyebrow">Technical information</p><h2>Product-family specifications.</h2><p className="section-note">Confirm size-specific dimensions, grade, coating, tolerance, applicable reference and availability in your quotation.</p></div><div className="spec-table">{handTapSpecs.map(([label, value]) => <div key={label}><strong>{label}</strong><span>{value}</span></div>)}</div></div></section>
    <section className="thread-section section"><div className="shell thread-grid"><div><p className="eyebrow">Thread families</p><h2>Find the thread<br /><em>you need.</em></h2><p>These are enquiry options, not a live inventory claim. Send the exact component drawing where a thread designation is ambiguous.</p></div><div className="thread-panels">{handTapThreadFamilies.map(([group, options]) => <div key={group}><strong>{group}</strong><span>{options}</span></div>)}</div></div></section>
    <section className="lead-section section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Lead and chamfer options</p><h2>Start clean.<br /><em>Finish close.</em></h2></div><p>Choose the lead according to the entry, thread depth and hole condition. The corresponding configuration is confirmed in the quotation.</p></div><div className="lead-grid">{leadOptions.map(([title, lead, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><strong>{lead}</strong><p>{text}</p></article>)}</div></div></section>
    <section id="applications" className="applications-section section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Application examples</p><h2>Your component.<br /><em>Your industry.</em></h2></div><p>Discuss this application with the manufacturer. Suitability depends on the drawing, material, machine, hole and production quantity.</p></div><div className="industry-grid">{handTapIndustries.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><a href="#enquiry">Discuss this application <span aria-hidden="true">↗</span></a></article>)}</div></div></section>
    <section className="product-video section"><div className="shell product-two-column"><div className="product-video-frame"><div className="video-placeholder"><span>FACTORY INTRODUCTION</span><h3>From steel to threads</h3><a href="https://www.youtube.com/watch?v=BHTs56TPKFg" target="_blank" rel="noreferrer">Watch on YouTube <span aria-hidden="true">↗</span></a></div></div><div><p className="eyebrow">Technical support</p><h2>See the work behind the name.</h2><p>The available company video is a factory introduction, not a hand-tap performance test. For a product working demonstration, share your application and request a verified video.</p><a className="under-link" href={`mailto:${company.email}?subject=Request%20a%20working%20video%20for%20HSS%20hand%20tap`}>Request a working video <span aria-hidden="true">↗</span></a></div></div></section>
    <section className="quality-section section"><div className="shell product-two-column"><div><p className="eyebrow">Quality and partnership</p><h2>Quality in the tool.<br /><em>Confidence in the partner.</em></h2></div><div className="quality-list"><p>Bring the application, specification and commercial requirement together in a clear quotation.</p><span>Application-led discussion with the manufacturer.</span><span>Listed material-grade and hardness options.</span><span>Ground-thread finish and tolerance review.</span><span>Standard, bulk, export and drawing-led custom enquiries.</span><span>Quotation confirming specification and commercial terms.</span><Link className="under-link" href="#enquiry">Request ISO certificate &amp; company profile <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="order-modes section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Commercial order paths</p><h2>One product.<br /><em>Four ways forward.</em></h2></div><p>Prices, MOQ, freight, tax, lead time and payment terms are confirmed for the selected configuration. No universal commercial promise is published here.</p></div><div className="mode-grid"><a href="#enquiry"><span>01</span><h3>Standard enquiry</h3><p>Size, pitch, material and quantity.</p><b>Get product quote ↗</b></a><a href="#enquiry"><span>02</span><h3>Bulk order</h3><p>Size-wise quantities and repeat requirements.</p><b>Request bulk quotation ↗</b></a><a href="#enquiry"><span>03</span><h3>Export enquiry</h3><p>Destination, documents and delivery terms.</p><b>Discuss export order ↗</b></a><a href="#enquiry"><span>04</span><h3>Custom made</h3><p>Drawing, revision, length and tolerance.</p><b>Request custom review ↗</b></a></div></div></section>
    <section id="enquiry" className="product-enquiry section"><div className="shell product-two-column"><div><p className="eyebrow">HSS hand tap enquiry</p><h2>Tell us what you need.<br /><em>We’ll help find the tool.</em></h2><p>Share your thread, material, quantity or drawing reference. The form prepares an email draft for review; it does not claim to submit to a CRM.</p><div className="contact-list"><a href={company.phoneHref}>{company.phone}</a><a href={`mailto:${company.email}`}>{company.email}</a><a href={company.whatsapp} target="_blank" rel="noreferrer">WhatsApp us <span aria-hidden="true">↗</span></a></div></div><ProductEnquiryForm /></div></section>
    <section id="faqs" className="faq-section section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Buyer questions</p><h2>Clear answers<br /><em>before you order.</em></h2></div></div><div className="faq-list">{handTapFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="related-products section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Continue exploring</p><h2>Related tools<br /><em>for the job.</em></h2></div><p>Review neighbouring products or return to the HSS hand-tap family when the application needs a different production approach.</p></div><div className="related-grid"><Link href="/products/hss-hand-taps"><Image src="/images/products/hss-hand-tap-set.jpg" alt="HSS hand tap set" fill sizes="(max-width: 560px) 100vw, 33vw" /><strong>HSS Hand Tap Set</strong></Link><Link href="/get-a-quote"><Image src="/images/products/hss-machine-tap.jpg" alt="HSS machine tap" fill sizes="(max-width: 560px) 100vw, 33vw" /><strong>HSS Machine Tap</strong></Link><Link href="/get-a-quote"><Image src="/images/products/hss-nut-tap.jpg" alt="HSS nut tap" fill sizes="(max-width: 560px) 100vw, 33vw" /><strong>HSS Nut Tap</strong></Link></div></div></section>
  </main></SiteShell>;
}